catalog/urls.py
from django.urls import path
from . import views

urlpatterns=[

path('',views.index, name="index"),
path('books/', views.BookListView.as_view(template_name='book_list.html'), name='books'),
path('books/<int:pk>/', views.BookDetailView.as_view(template_name='book_details.html'), name='book_details'),
path('authors/',views.AuthorListView.as_view(template_name='author_list.html'), name='authors'),
path('authors/<int:pk>/', views.AuthorDetailView.as_view(template_name='author_details.html'), name='author_details'),
path('mybooks/',views.LoanedBooksByUserListView.as_view(),name='my_books'),
path('allborrows/',views.LoanedBooksByAllUsersListView.as_view(),name='all_books'),

]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/'),
    )
]
urlpatterns +=[  path('accounts/', include('django.contrib.auth.urls')),
                ]

catalog/models.py
from django.db import models
from django.urls import reverse
import uuid
from django.contrib.auth.models import User
from datetime import date

class Genre(models.Model):
	'''this model represent book genre'''
	name= models.CharField(max_length=50, help_text="enter a Genre (ex:science fiction)")

	def __str__(self):
		"""String for representing the Model object."""
		return self.name




class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete= models.SET_NULL,null=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_back']
        permissions =(('can_mark_returned','set book as returned'),)

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'

    def status_display(self):

        return [self.LOAN_STATUS[i][1] for i in range(len(self.LOAN_STATUS)) if self.status == self.LOAN_STATUS[i][0] ][0]

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

        
class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('author_details', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return self.full_name()

    def full_name(self):
        return self.first_name+' '+self.last_name

class Book(models.Model):
    '''this models represents a book and storesa all the detials of the book except for he instance of book for loan'''
    title = models.CharField(max_length=50, help_text="enter name of the book (eg: pristage)")
    isbn =models.CharField('ISBN',max_length=13, unique=True,
                                         help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')

    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary =models.TextField(max_length=1000, help_text='enter a breif summary of the book')

    genre= models.ManyToManyField(Genre, help_text='select genre of the book')


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book_details', args=[str(self.id)])
     
    def display_genre(self):
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description="genre"

catalog/views.py
from django.shortcuts import render
from .models import Book, BookInstance, Author, Genre
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin

# Create your views here.

def index(request):
	num_books = Book.objects.all().count()
	num_authors = Author.objects.all().count()
	num_books_avaliable = BookInstance.objects.filter(status__exact='a').count()
	num_book_instance = BookInstance.objects.all().count()
	genre = Genre.objects.all()
	books_genre=[gen.name for gen in genre]
	num_visits = request.session.get('num_visits', 0)
	request.session['num_visits'] = num_visits + 1 

	context ={"book_count":num_books,
			"book_instance_count":num_book_instance,
			"avaliable_books":num_books_avaliable,
			"authors_count":num_authors,
			'genre':books_genre,
			"num_visits":num_visits}

	return render(request, "index.html",context=context)


class BookListView(generic.ListView):
	model = Book

class BookDetailView(generic.DetailView):
	model = Book
class AuthorListView(generic.ListView):
	model=Author

class AuthorDetailView(generic.DetailView):
	model=Author

class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
	model= BookInstance
	template_name = 'bookinstance_borrowed_by_user.html'
	paginate_by=10

	def get_queryset(self):
		return BookInstance.objects.filter(borrower =self.request.user).filter(status__exact='o').order_by('due_back')



class LoanedBooksByAllUsersListView(LoginRequiredMixin,PermissionRequiredMixin, generic.ListView):
	model= BookInstance
	template_name = 'bookinstance_borrowed_by_all_user.html'
	paginate_by=10
	permission_required = 'catalog.can_mark_returned'

	def get_queryset(self):
		return BookInstance.objects.filter(status__exact='o').order_by('due_back')

catalog/templates/author_details.html
{%extends 'base_template.html'%}
{% block title %} {{author.full_name}} {%endblock%}

{% block content %}
<h1>Author: {{author.full_name}}</h1>

<p> {{author.date_of_birth}} -{% if author.date_of_death %} {{author.date_of_death}} {%endif%}</p>

<div class="ml-2">
<h3 class="ms-2 "><strong>Books</strong></h3>

{% for book in author.book_set.all%}
<div class="book_view mb-1">
<p><a href="{{book.get_absolute_url}}"><strong>{{book.title}}</strong></a> ({{book.bookinstance_set.all.count}})</p>
<p>{{book.summary}}</p>
</div>
{%endfor%}
</div>

{% endblock %}

catalog/templates/author_list.html
{% extends 'base_template.html'%}

{% block title %} Authors {%endblock%}

{% block content%}
<h2>Authors</h2>
<ul>
{% for author in author_list%}

<li><a href="{{ author.get_absolute_url }}" class="capitalize ">{{author.full_name}}</a></li>
{% endfor%}
</ul>
{% endblock %}

catalog/templates/base_template.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<title>{%block title%} Book catalog {%endblock%}</title>
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css'%}">

</head>
<body>

	<aside>
		{%block sidebar%}
		<ul>
			<li><a href="{% url 'index' %}">Home</a> </li>
			<li><a href="{% url 'books' %}">Books</a> </li>
			<li><a href="{% url 'authors' %}">Authors</a> </li>
		</ul>

		
		<ul>
			{%if user.is_authenticated %}
			<li class="capitalize">{{request.user}}</li>
			<li class=""><a href="{% url 'my_books' %}">My Books</a></li>
			<li><a href="{% url 'logout' %}">logout</a></li>
			{%else%}
			<li><a href="{% url 'login' %}">login</a></li>
			{%endif%}
			</ul>
	
		<ul>
			{%if perms.catalog.can_mark_returned %}
			<li>Staff Member</li>
			<li><a href="{% url 'all_books' %}">All Barrows</a></li>
			{%endif%}
		</ul>

	
		{%endblock%}
	</aside>
	<section>
		{%block content%}
		{%endblock%}
	<section>
	


</body>
</html>

catalog/templates/book_details.html
{% extends 'base_template.html' %}

{% block title %}{{book.title}}{% endblock %}
{% block content %}
<h2>Title: {{book.title}}</h2>

<p><strong>Author: </strong> <a href="{{book.author.get_absolute_url}}">{{book.author}}</a></p>
<p><strong>Summary: </strong> {{book.summary}}</p>
<p><strong>ISBN: </strong> {{book.isbn}}</p>
<p><strong>Genre: </strong> {{book.genre.all|join:', '}}</p>

{% if book.bookinstance_set.all %}
<div class="ms-2 ml-2">

<h3><strong>Copies</strong></h3>
	
{% for copy in book.bookinstance_set.all %}
<div class="ms-4">
<p class="{%if copy.status == 'a'%}text success{% elif copy.status == 'm'%}text danger{%else%}text warning {% endif%}"><strong>{{copy.status_display}}</strong></p>
{% if copy.status != 'a' %}
<p>Due to be returned: {{copy.due_back}}</p>
{% endif %}
<p>Imprint: {{copy.imprint}}</p>
<p>Id: {{copy.id}}</p>
</div>
{% endfor %}

</div>
{%else%}
<h3 class="ms-4"><strong>No copies available</strong></h3>
{%endif%}


{% endblock %}

catalog/templates/book_list.html
{% extends 'base_template.html' %}

{% block title %} books {% endblock %}

{% block content %}

{% if book_list %}
<p>Available Books </p>
<ul>
{% for book in book_list %}
<li class="capitalize"><a href="{{book.get_absolute_url}}">{{book.title}}</a> ({{book.author}})</li>
{% endfor %}
</ul>
{% else %}
<p> No books avaliable</p>
{% endif %}

{% endblock %}

catalog/templates/bookinstance_borrowed_by_all_user.html
{% extends 'base_template.html' %}

{% block title%}Books Borrowed {% endblock %}

{% block content %}
<h1>all barrows</h1>
<ul>
{% for bookinst in bookinstance_list %}

<li class="{% if bookinst.is_overdue%} text-danger {%endif%}"><a href="{{bookinst.book.get_absolute_url}}">{{bookinst.book.title}}</a>  Due Date: {{bookinst.due_back}} (Barrower: {{bookinst.borrower}})</li>
{%endfor%}
{% endblock%}

catalog/templates/bookinstance_borrowed_by_user.html
{% extends 'base_template.html'%}

{% block title %}My Books{%endblock%}
{% block content%}
<h2>Borrowed Books</h2>
<ul>
{% for bookinst in bookinstance_list%}
<li class="{% if bookinst.is_overdue%} text-danger {%endif%}"><a href="{{bookinst.book.get_absolute_url}}">{{bookinst.book.title}}</a> ({{bookinst.due_back}})</li>
{%endfor%}
</ul>
{% endblock%}

catalog/templates/index.html
{% extends "base_template.html" %}

{%block title%}index{%endblock%}

{%block content%}
<h1>the local library</h1>
<p>welcome to local library developed by Mr.chandu kishore</p>
<h2>Dynamic content</h2>
<p>this libaray contains following content counts:</p>
<ul>
	<li><span>Books:</span> {{book_count}}</li>
	<li><span>Authors:</span> {{authors_count}}</li>
	<li><span>Copies:</span> {{book_instance_count}}</li>
	<li><span>Copies Available:</span> {{avaliable_books}}</li>
	<li><span>Genre Available: </span> {{genre}}</li>

</ul>
<p> you have visited this page {{num_visits}} time{{num_visits|pluralize}}</p>

{%endblock%}